Repository lisiCAO/QLMS, pull requests merged in 2024-02, with the labels that each got.

#38 Feature/client layout
  client/package-lock.json
  client/package.json
  client/public/default_user.png
  client/public/logo.png
  client/src/App.js
  client/src/assets/_variables.scss
  client/src/components/forms/CustomForm.jsx
  client/src/components/forms/ForgotPassword.jsx
  client/src/components/forms/LoginForm.jsx
  client/src/components/forms/NewLeaseApplication.jsx
  client/src/components/forms/Registration.jsx
  client/src/components/forms/RoleSelection.scss
  client/src/components/hooks/useUnloadMessage.jsx
  client/src/components/landlord/LandlordProfile.jsx
  client/src/components/landlord/leases/LeaseCreate.jsx
  client/src/components/landlord/leases/LeaseList.jsx
  client/src/components/landlord/properties/PropertyCreate.jsx
  client/src/components/landlord/properties/PropertyCreate.scss
  client/src/components/landlord/properties/PropertyDelete.jsx
  client/src/components/landlord/properties/PropertyEdit.jsx
  client/src/components/landlord/properties/PropertyList.jsx
  client/src/components/landlord/properties/PropertyList.scss
  client/src/components/landlord/tenants/TenantDelete.jsx
  client/src/components/landlord/tenants/TenantEdit.jsx
  client/src/components/landlord/tenants/TenantUpdate.jsx
  client/src/components/landlord/tenants/TenantsList.jsx
  client/src/components/layout/LogoutModal.jsx
  client/src/components/layout/NavDivider.jsx
  client/src/components/layout/OnBoardingStep.scss
  client/src/components/layout/OnBoardingSteps.jsx
  client/src/components/layout/Sidebar.jsx
  client/src/components/layout/Sidebar.scss
  client/src/components/layout/TenantNavbar.jsx
  client/src/components/layout/Topbar.jsx
  client/src/components/layout/Topbar.scss
  client/src/components/properties/CreateProperty.jsx
  client/src/components/properties/ListOfProperties.jsx
  client/src/components/tenant/LeaseApply.jsx
  client/src/components/tenant/LeaseView.jsx
  client/src/components/tenant/PropertyGeneralList.jsx
  client/src/components/tenant/TenantDashbord.jsx
  client/src/components/tenant/TenantProfile.jsx
  client/src/context/SearchContext.js
  client/src/context/authContext.js
  client/src/index.js
  client/src/pages/AuthPage.jsx
  client/src/pages/AuthPage.scss
  client/src/pages/landlord/LandlordLayout.jsx
  client/src/pages/landlord/Layout.scss
  client/src/pages/landlord/lease/LeasePage.jsx
  client/src/pages/landlord/property/PropertyPage.jsx
  client/src/pages/landlord/tenant/LandlordTenantPage.jsx
  client/src/pages/tenant/TenantLayout.jsx
  client/src/pages/tenant/TenantPage.jsx
  client/src/services/ApiService.js
  client/src/services/ProtectedRoute.js
Labels: enhancement

#42 Feature/client
  client/package-lock.json
  client/package.json
  client/public/default_user.png
  client/public/logo.png
  client/src/App.js
  client/src/assets/_variables.scss
  client/src/components/forms/CustomForm.jsx
  client/src/components/forms/ForgotPassword.jsx
  client/src/components/forms/LoginForm.jsx
  client/src/components/forms/NewLeaseApplication.jsx
  client/src/components/forms/Registration.jsx
  client/src/components/forms/RoleSelection.scss
  client/src/components/hooks/useUnloadMessage.jsx
  client/src/components/landlord/LandlordProfile.jsx
  client/src/components/landlord/leases/LeaseCreate.jsx
  client/src/components/landlord/leases/LeaseDelete.jsx
  client/src/components/landlord/leases/LeaseList.jsx
  client/src/components/landlord/properties/PropertyCreate.jsx
  client/src/components/landlord/properties/PropertyCreate.scss
  client/src/components/landlord/properties/PropertyDelete.jsx
  client/src/components/landlord/properties/PropertyEdit.jsx
  client/src/components/landlord/properties/PropertyList.jsx
  client/src/components/landlord/properties/PropertyList.scss
  client/src/components/landlord/tenants/TenantDelete.jsx
  client/src/components/landlord/tenants/TenantEdit.jsx
  client/src/components/landlord/tenants/TenantUpdate.jsx
  client/src/components/landlord/tenants/TenantsList.jsx
  client/src/components/layout/LogoutModal.jsx
  client/src/components/layout/NavDivider.jsx
  client/src/components/layout/OnBoardingStep.scss
  client/src/components/layout/OnBoardingSteps.jsx
  client/src/components/layout/Sidebar.jsx
  client/src/components/layout/Sidebar.scss
  client/src/components/layout/TenantNavbar.jsx
  client/src/components/layout/Topbar.jsx
  client/src/components/layout/Topbar.scss
  client/src/components/properties/CreateProperty.jsx
  client/src/components/properties/ListOfProperties.jsx
  client/src/components/tenant/LeaseApplication.jsx
  client/src/components/tenant/LeaseView.jsx
  client/src/components/tenant/PropertyDetail.jsx
  client/src/components/tenant/PropertyGeneralList.jsx
  client/src/components/tenant/TenantDashboard.jsx
  client/src/components/tenant/TenantProfile.jsx
  client/src/context/AuthContext.js
  client/src/context/SearchContext.js
  client/src/index.js
  client/src/pages/AuthPage.jsx
  client/src/pages/AuthPage.scss
  client/src/pages/landlord/LandlordLayout.jsx
  client/src/pages/landlord/Layout.scss
  client/src/pages/landlord/lease/LeasePage.jsx
  client/src/pages/landlord/property/PropertyPage.jsx
  client/src/pages/landlord/tenant/LandlordTenantPage.jsx
  client/src/pages/tenant/TenantLayout.jsx
  client/src/pages/tenant/TenantPage.jsx
  client/src/services/ApiService.js
  client/src/services/ProtectedRoute.js
Labels: enhancement

#45 Feature/server crud/lease base on develop
  server/config/config.js
  server/src/controllers/authController.js
  server/src/controllers/leaseController.js
  server/src/controllers/propertyController.js
  server/src/controllers/userController.js
  server/src/models/lease.js
  server/src/models/property.js
  server/src/models/user.js
  server/src/routes/leaseRoutes.js
  server/src/routes/propertyRoutes.js
  server/src/routes/userRoutes.js
  server/src/server.js
  server/src/services/leaseService.js
  server/src/services/propertyService.js
  server/src/services/userImageService.js
  server/src/services/userService.js
Labels: feature

#46 Feature/client
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/account/AccountProfile.jsx
  client/src/components/account/AccountProfileDetail.jsx
  client/src/components/account/UserProfile.jsx
  client/src/components/layout/Sidebar.jsx
  client/src/components/layout/Sidebar.scss
  client/src/components/layout/TenantNavbar.jsx
  client/src/components/layout/Topbar.jsx
  client/src/components/layout/Topbar.scss
  client/src/components/tenant/TenantProfile.jsx
  client/src/pages/landlord/LandlordLayout.jsx
  client/src/pages/landlord/LandlordProfile.jsx
  client/src/pages/landlord/Layout.scss
  client/src/pages/landlord/property/PropertyPage.jsx
  client/src/pages/tenant/TenantPage.jsx
  client/src/pages/tenant/TenantProfile.jsx
Labels: enhancement

#49 Feature/client authcontext
  client/src/App.js
  client/src/components/forms/LoginForm.jsx
  client/src/components/layout/Sidebar.jsx
  client/src/components/layout/TenantNavbar.jsx
  client/src/components/layout/Topbar.jsx
  client/src/context/AuthContext.js
  client/src/index.js
  client/src/pages/tenant/TenantLayout.jsx
  client/src/services/ApiService.js
Labels: enhancement

#50 Bug/server/auth
  server/src/controllers/authController.js
  server/src/controllers/userController.js
  server/src/services/userService.js
Labels: bug

#51 Feature/client
  client/src/App.js
  client/src/components/forms/LoginForm.jsx
  client/src/components/layout/Sidebar.jsx
  client/src/components/layout/TenantNavbar.jsx
  client/src/components/layout/Topbar.jsx
  client/src/context/AuthContext.js
  client/src/index.js
  client/src/pages/tenant/TenantLayout.jsx
  client/src/services/ApiService.js
Labels: bug

#58 Hotfix/nologin redirect
  README.md
  client/src/context/AuthContext.js
  client/src/services/ApiService.js
  client/src/services/CheckAuth.js
Labels: bug

#59 add get lease for current landlord
  server/src/controllers/leaseController.js
  server/src/routes/leaseRoutes.js
  server/src/services/leaseService.js
Labels: feature

#61 Feature/server
  server/src/controllers/leaseController.js
  server/src/routes/leaseRoutes.js
  server/src/services/leaseService.js
Labels: enhancement
